## Logistic Regression

$Z = w^T \cdot X + b$

$A = \sigma(Z)$

**Loss function for a single observation:**

$L = \hat{y}^{y}(1-\hat{y})^{1-y}$

$log(L) = y*log(\hat{y})+(1-y)*log(1-\hat{y})$

**Logistic Regression cost function:**

$J(w, b) = -\frac{1}{m} \sum_{i=1}^{m}(y_{i}*log(\hat{y_{i}})+(1-y_{i})*log(1-\hat{y_{i}}))$

## Neural Networks

In [3]:
import numpy as np

A = np.random.randn(4, 3)
B = np.sum(A, axis=1, keepdims=True)

print(A)
print(B)

[[-0.44587644 -0.49530091 -1.93062692]
 [-1.68901018  0.63626484  1.50759355]
 [-0.55579423 -0.76611873 -0.04216447]
 [ 1.00616281 -0.34852588  0.05968195]]
[[-2.87180427]
 [ 0.45484822]
 [-1.36407743]
 [ 0.71731888]]
