In [ ]:
## Intro to TensorFlow

In [4]:
import tensorflow as tf
tf.__version__

'1.2.1'

### Basic Graph

In [6]:
# define the variables
x = tf.Variable(3, name = 'x')
y = tf.Variable(4, name = 'y')

# define the function
f = x*x*y + y + 2

# initialize the TF session
sess = tf.Session()

# initialize the variables
sess.run(x.initializer)
sess.run(y.initializer)

# run the function
result = sess.run(f)
print(result)
sess.close()  # close the session

42


### Alternative Session Notation

In [9]:
# initialize every variable in turn
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()

print(result)

# initialize all the variable at the same time
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    result = f.eval()

print(result)

42
42


### Linear Regression

In [22]:
import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
housing.data[0]

array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ])

In [16]:
housing.data.shape

(20640, 8)

In [19]:
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

In [21]:
housing_data_plus_bias[0]

array([   1.        ,    8.3252    ,   41.        ,    6.98412698,
          1.02380952,  322.        ,    2.55555556,   37.88      , -122.23      ])

In [26]:
# define the graphs
X = tf.constant(housing_data_plus_bias, dtype = tf.float32, name = "X")
y = tf.constant(housing.target.reshape(-1, 1), dtype = tf.float32, name = "y")
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

In [28]:
# run the session
with tf.Session() as sess:
    theta_value = theta.eval()
    
print(theta_value)

[[ -3.74651413e+01]
 [  4.35734153e-01]
 [  9.33829229e-03]
 [ -1.06622010e-01]
 [  6.44106984e-01]
 [ -4.25131839e-06]
 [ -3.77322501e-03]
 [ -4.26648885e-01]
 [ -4.40514028e-01]]
